package creditcard.ui;

import creditcard.account.AbstractAccount;
import creditcard.facade_DB.CreditCardFacade;
import framework.account.IAccount;
import framework.party.Customer;


public class JDialogGenBill extends javax.swing.JDialog
{
	private CardFrm cardFrm;
	private CreditCardFacade facade;

	public JDialogGenBill(CardFrm cardFrm, CreditCardFacade facade)
	{
		this.cardFrm = cardFrm;
		this.facade = facade;
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parses  your Java file into its visual envirenment.
		//{{ INIT_CONTROLS
		getContentPane().setLayout(null);
		setSize(405,367);
		setVisible(false);
		getContentPane().add(JScrollPane1);
		JScrollPane1.setBounds(24,24,358,240);
		JScrollPane1.getViewport().add(JTextField1);
		JTextField1.setBounds(0,0,355,237);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(156,276,96,24);

		// generate the string for the monthly bill

		String billstring = "";
		for(Customer party: facade.getCustomers()) {
			for(IAccount account: party.getAccounts()) {
				AbstractAccount ccAccount = (AbstractAccount) account;

				billstring += "Name= "+party.getName()+"\r\n";
				billstring += "CC number = "+account.getAccNumber()+"\r\n";
				billstring += "CC type = "+account.getType()+"\r\n";
				billstring += "Previous balance = $"+ccAccount.getLastMonthBalance()+"\r\n";
				billstring += "Total Credits = $"+ccAccount.getTotalCredits()+"\r\n";
				billstring += "Total Charges = $"+ccAccount.getCharges()+"\r\n";
				billstring += "New balance = $"+ccAccount.getNewMonthlyBalance()+"\r\n";
				billstring += "Total amount due = $"+ccAccount.getMonthlyAmountDue()+"\r\n";
				billstring += "\r\n";
				billstring += "\r\n";

			}
		}

		JTextField1.setText(billstring);

		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
	}

	//{{DECLARE_CONTROLS
	javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();
	javax.swing.JTextArea JTextField1 = new javax.swing.JTextArea();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event)
	{
		dispose();

	}
}
